### ISSUE TITLE
Alle 3 Werte in der Email/Datenbank anzeigen

### ISSUE THREAD

**Issue by bixicy** [christianbarkowsky/contao-protectedselect#16]
Hallo,

beim erstellen des **Geschütztes Select-Menü** gebe ich ja pro Zeile 3 Werte an. Gem. dem Beispiel ist das:
**key1**, **geheimer Wert 1** sowie **Ausgabe 1**

![image](https://user-images.githubusercontent.com/46830537/88033096-358c8080-cb3f-11ea-8ab7-e98f6ad88226.png)

Kann ich denn irgendwie alle 3 dieser Werte speichern lassen? Bzw. in der Ausgabe in der Email alle 3 Werte anzeigen lassen?

**Comment by christianbarkowsky** [comment]
Wieso willst du das anzeigen lassen? Der geschütze Wert soll doch geschützt bleiben?! @bixicy
