### ISSUE TITLE
unvollständige Installation?

### ISSUE THREAD

**Issue by samazaphikel** [christianbarkowsky/contao-protectedselect#17]
Hi,
es werden nach der Installation keine Tabellen angelegt. Ich habe Composer Cache gelöscht und anschließend Composer Update durchgeführt. Allerdings ohne Änderungen.

Dann habe ich die Erweiterung wieder gelöscht und neu hinzugefügt, danach das Installtool aufgerufen aber es werden keine Tabellen zum Hinzufügen/Updaten angeboten.

Nach der Installation im Formular der  Feldtyp Geschütztes Select-Menü wird nicht angezeigt.

Ich nutze Contao 4.9.3 und contao-protectedselect 1.20

**Comment by christianbarkowsky** [comment]
Ich kann das Problem nicht nachstellen @samazaphikel ... Just try again.

**Comment by thomasCcologne** [comment]
Ich habe das gleiche Problem bei einer Contao 4.9.9-Installation. Das Paket wird fehlerfrei installiert, aber keine Anpassung an der DB vorgenommen. Im Backend erhalte ich dann auch keinen neuen Feldtyp "Geschützes Select-Menü".

**Comment by thomasCcologne** [comment]
Nachtrag: Ich benutze das Premium Theme Eclipse X. Könnte diese zu den Problemen führen?

**Comment by christianbarkowsky** [comment]
Ich weiß leider nicht, was die Kollegen vom Premium Themes mit ihrem Eclipse so im Hintergrund machen.

**Comment by thomasCcologne** [comment]
Es scheint ja einige Themes zu geben, die die Formfelder leicht abändern (siehe https://github.com/christianbarkowsky/contao-protectedselect/issues/13 ). Wäre es da nicht sinnvoll ein eigenes Template (mit eigenem Namespace) in der Erweiterung zu hinterlegen?

**Comment by avoca77** [comment]
Auch bei mir das Problem in einer 4.4.55. Nach der Installation erhalte ich kein Feld "geschütztes Select-Menü". Die Contao-Installation läuft nur mit den Core-Modulen. Kann es sein, dass da irgendwelche Rudimente aus Contao 3 die Installation von protectedselect verhindern? Ich habe die Contao-Installation übernommen und weiß nicht, ob das Update von C3 auf C4 damals ordentlich gemacht wurde. Ich habe mal als Versuch von protectedselect die Version 1.1.4 installiert, da wird das Feld noch angelegt. Dann ab 1.1.5 nicht mehr.

**Comment by snarosy75** [comment]
Wollte eben die Erweiterung (aktuelle Version 1.1.2) in einer 4.9.11-Version installieren über den Contao Manager.
Der Testlauf funktionierte, im Zuge des composer install kam dann aber die Fehlermeldung 
`Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception
In ScriptHandler.php line 89:
                                                                        
  An error occurred while executing the "contao:symlinks web" command:  
                                                                        
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
# Process terminated with exit code 1
# Result: General error`
kann mit der Fehlermeldung leider nichts anfangen?

**Comment by christianbarkowsky** [comment]
Das sieht nicht nach m

> Wollte eben die Erweiterung (aktuelle Version 1.1.2) in einer 4.9.11-Version installieren über den Contao Manager.
> Der Testlauf funktionierte, im Zuge des composer install kam dann aber die Fehlermeldung
> `Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception
> In ScriptHandler.php line 89:
> 
> An error occurred while executing the "contao:symlinks web" command:
> 
> install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [...]
> # Process terminated with exit code 1
> # Result: General error`
> 
> kann mit der Fehlermeldung leider nichts anfangen?

Das sieht nicht nach meiner Erweiterung aus. @snarosy75
