### ISSUE TITLE
Erweiterung funktioniert nicht unter Contao 4.9.31

### ISSUE THREAD

**Issue by dennisbohn** [christianbarkowsky/contao-protectedselect#19]
Moin, ich habe heute die Erweiterung auf einer bestehenden Contao-Instanz installiert. Leider wird mir nach der Installation weder ein zusätzlicher Datenbank-Eintrag im Install-Tool angezeigt, noch taucht das Feld im Backend auf.

Das Problem lässt sich bei mir wie folgt reproduzieren:

- Frische Installation von Contao 4.9.31 (Core) über den Contao Manager
- Anlegen der Datenbank-Felder über das Install-Tool
- Installation von "contao-protectedselect" über den Contao Manager

Wenn ich daraufhin das Install-Tool aufrufe, erhalte ich die Meldung "Die Datenbank ist aktuell.".

**Comment by jaynoe** [comment]
Ich hatte das Problem auch. Aufgefallen ist mir, dass laut composer.json das Modul unter system/modules existieren sollte - tut es aber nicht.

Lad dir das neuste Release hier mal runter und lade es in system/modules hoch, wie es in der autoload.php steht:
`system/modules/protectedselect/`

Dann mal composer update und alles sollte wieder da sein & funktionieren.

**Comment by dennisbohn** [comment]
Danke für den Tipp. Wenn ich in ./system/modules einen Symlink auf den Ordner ./vendor/christianbarkowsky/contao-protectedselect setze, klappt es ebenfalls.

```
cd system/modules
ln -s ../../vendor/christianbarkowsky/contao-protectedselect protectedselect
```

**Comment by christianbarkowsky** [comment]
Hey @dennisbohn @jaynoe,

gucke ich mir morgen an. Sorry!

**Comment by christianbarkowsky** [comment]
Hey @dennisbohn @jaynoe,

die Erweiterung ist nun ein Bundle ... der Fehler sollte jetzt verschwunden sein.
Bitte testen. 🙇

**Comment by dennisbohn** [comment]
Klappt wunderbar. Vielen Dank!
