### ISSUE TITLE
Inserttag für Bezeichnung

### ISSUE THREAD

**Issue by stefan-at-work** [christianbarkowsky/contao-protectedselect#21]
Habe als geschützen Wert eMail-Adessen. Im Notification-Center möchte ich jedoch nicht den Wert, sondern die Bezeichnung ausgeben. Es wäre schön, wenn hierfür im Modul ein Inserttag zur Verfügung stehen würde.

**Comment by kroerig** [comment]
Ich stehe gerade auch vor diesem Problem. Ist da was möglich?

**Comment by christianbarkowsky** [comment]
Hey @kroerig ja - es ist möglich.

**Comment by kroerig** [comment]
Super. Wenn ich das richtig lese, dann ist der Wunsch https://github.com/christianbarkowsky/contao-protectedselect/issues/18#issue-872218420  identisch, oder?

**Comment by cocree** [comment]
@christianbarkowsky Mit welchem Inserttag / Simple Token wird die Bezeichnung ausgegeben?

**Comment by christianbarkowsky** [comment]
Hey @cocree ganz normal wie im Notificaiton center ##form_NAME_DES_FELDES##

**Comment by christianbarkowsky** [comment]
Sorry @cocree  {{protected_select::NAME::label}}
