### ISSUE TITLE
Neue Select-Optionen nicht anklickbar

### ISSUE THREAD

**Issue by ngdot** [christianbarkowsky/contao-protectedselect#3]
Sobald ich ein neue Select-Option mit dem "+" hinzufüge, ist es nicht möglich mit einem normalen Linksklick die kopierten Werte bzw. die leeren Felder zu füllen. Drag & Drop funktioniert. Mit einem Rechtsklick kann ich das Feld editieren, anders leider nicht. Bug?

Getestet unter Contao LTS 3.5.17 / Default Backend-Theme

**Comment by fenepedia** [comment]
Kann den Bug bestätigen. Ich kann die Felder nur auswählen, wenn ich erst einen Rechtsklick mache oder wenn ich auf die Felder mit der Tab-Taste springe.

Denke das hat etwas mit dem JavaScript zu tun, dass die Reihenfolge per Drag&Drop anpasst.

**Comment by Toflar** [comment]
Kann ich ebenfalls bestätigen :)

**Comment by christianbarkowsky** [comment]
wird gefixed ... aber bitte gibt mir noch n paart tage ... ich mach noch n bissl pause.

**Comment by christianbarkowsky** [comment]
@NicolasGoerlach @fenepedia @Toflar ... funktioniert nun wieder so wie es soll.
