### ISSUE TITLE
Works on Contao 4?

### ISSUE THREAD

**Issue by Olli** [christianbarkowsky/contao-protectedselect#4]
Hi,
does this extension work with contao 4?
I would try it but I don't know how to "force install" a extension if it doesn't like any dependency is unsatisfied.

**Comment by Olli** [comment]
Ok I'd install the new version. 
One error occours, after the protected field was added and I try to edit the form again:
´´´
Was ist das Problem?

Could not find template "form_widget"
´´´


Next problem - the classes tl_text_2 and tl_text_4 seam to be to small. 

Third problem: while try to save the protected fields, I got the " Ungültiges Anfrage-Token" message while trying to add a protected field.

**Comment by Olli** [comment]
The output array for the select isn't also not filled.

**Comment by Olli** [comment]
Anyone home? :)

**Comment by christianbarkowsky** [comment]
Nope #urlaub

**Comment by Olli** [comment]
NP HF :)

**Comment by Olli** [comment]
#urlaub vorbei? :)

**Comment by Olli** [comment]
Wird die Erweiterung aufgegeben? Welche Alternative habe ich?

**Comment by christianbarkowsky** [comment]
Hallo. Die Erweiterung wird natürlich nicht aufgegeben.

**Comment by arno1979** [comment]
Ich bin auch gerade auf die beschriebenen Probleme gestoßen.
Die `form_widget.html5` Template Datei gibt es in Contao 4 einfach nicht mehr, sie wird aber in `FormProtectedSelectMenu.php` auf Zeile 26 als Template-Variable gesetzt:
`protected $strTemplate = 'form_widget';`
Ich habe mir einfach die Datei von einer Contao 3 Installation geholt und ins `/templates` Verzeichnis gelegt. Damit funktioniert es zumindest technisch wieder bei mir.

Generell müsste die Erweiterung aber einfach für Contao 4 überarbeitet werden, weil gerade in Bezug auf die Formularfeldwidgets viele Änderungen passiert sind.
Das betrifft eben auch die Darstellung des Option Wizards im Backend. Die dort für die Größen der Input-Felder verwendeten CSS-Klassen gibt es einfach nicht mehr und einfach nur `tl_text` funktioniert nur eingeschränkt, weil einfach nicht genug Platz in der Breite vorhanden ist.

**Comment by Schmidty2** [comment]
Ist ein Zeitraum geplant, bis wann die Erweiterung für Contao 4.4 (4.6) verfügbar ist?
Oder ist eine finanzielle Unterstützung notwendig?
Wenn ja, bitte ich um kurze PN, Danke.

**Comment by GMTeams** [comment]
Ich wäre ebenfalls an der Erweiterung in Contao 4.4 interessiert.

**Comment by wiphi** [comment]
dmolineus Fork wäre auf ein Lösungsvorschlag: https://github.com/dmolineus/contao-protectedselect
Derzeit existiert keine offizielle, lauffähige Version für Contao 4, obwohl die composer.json was anderes sagt... Sehr ärgerlich. @christianbarkowsky, es wäre schön, wenn wir wieder eine offizielle Version bekommen könnten. Die Erweiterung ist doch sehr hilfreich!

**Comment by christianbarkowsky** [comment]
@wiphi na dann mache ich die Woche mal alle glücklich. 🚀

**Comment by wiphi** [comment]
Mit diesen https://github.com/wiphi/contao-protectedselect Änderungen habe ich die Erweiterung mittlerweile ganz gut am laufen ;)
Gerne kannst du sie übernehmen. Ich wollte noch einen CSV Import als Funktion wie bei der normalen select-Komponente hinzufügen, bin aber derzeit noch nicht weit gekommen.

**Comment by christianbarkowsky** [comment]
Ich merge mal das ganze Zeugs und spiele ein.

**Comment by christianbarkowsky** [comment]
Done. 🙏 @Olli @dmolineus @wiphi und an alle anderen fürs warten. :)
