### ISSUE TITLE
Contao 4.7 support

### ISSUE THREAD

**Issue by christianbarkowsky** [christianbarkowsky/contao-protectedselect#7]

**Comment by contaoacademy** [comment]
Wie ist hier eigentlich der Stand? Funktioniert die Erweiterung mit dem aktuellen Contao?

**Comment by christianbarkowsky** [comment]
Nach dem Urlaub setze ich mich ran.

**Comment by contaoacademy** [comment]
Hey @christianbarkowsky, schaffst du dieses Jahr noch eine Version die mit Contao 4.8 läuft?

**Comment by christianbarkowsky** [comment]
JA @contaoacademy
